#!/usr/bin/php
<?php

#
#  VGWhoIs (ViaThinkSoft Global WhoIs, a fork of generic Whois / gwhois)
#  Subprogram: cu TLD whois
#
#  (c) 2011-2024 by Daniel Marschall, ViaThinkSoft <info@daniel-marschall.de>
#
#  License: https://www.gnu.org/licenses/gpl-2.0.html (GPL version 2)
#

require_once __DIR__ . '/../../shared/php_includes/common_functions.inc.php';

ini_set('default_charset', 'UTF-8');

$domain = isset($argv[1]) ? $argv[1] : '';

define('BEGIN', '<!-- InstanceBeginEditable name="MainRgn" -->');
define('END',   '<!-- InstanceEndEditable -->');

$url = "https://www.nic.cu/dom_det.php?domsrch=$domain";

$res  = "% Parsing via regex from '$url'\n\n";

$x = file_get_contents2($url);

preg_match_all('@'.preg_quote(BEGIN, '@').'(.*)'.preg_quote(END, '@').'@ismU', $x, $m);

if (!isset($m[1][0])) {
	echo "Error while parsing the web content (RegEx failed).\n";
	exit(1);
}

$x = $m[1][0];

$x = strip_tags($x);

$x = str_replace('&nbsp;', ' ', $x);

$x = html_entity_decode($x);

$x = preg_replace("| +|", ' ', $x);
$x = preg_replace("|\n *|", "\n", $x);
$x = preg_replace("| *\n|", "\n", $x);
$x = preg_replace("|\n+|", "\n", $x);

$x = str_replace(":\n", ": ", $x);

$special_words = array(
	'Detalles del dominio',
	'Información general del dominio',
	'DNS Primario',
	'Contacto Técnico',
	'Contacto Administrativo',
	'Contacto Financiero'
);

foreach ($special_words as $s) {
	$x = str_replace($s, "\n".mb_strtoupper($s)."\n", $x);
}

$x = str_replace('< Regresar a la página anterior', '', $x);

$x = make_tabs($x);

$x = trim($x);

if (preg_match('@Dominio: *Organización: *Dirección:@', $x)) {
	$x = 'Domain does not exist.';
}

echo $res.trim_each_line($x)."\n";
