#!/bin/bash

#
#  generic Whois - Automatic Pattern Generator: Whois Ping Cronjob
#
#  (c) 2012-2014 Daniel Marschall, ViaThinkSoft [www.viathinksoft.de]
#
#  Distribution, usage etc. pp. regulated by the current version of GPL.
#
#
#  Version 2014-04-08
#

DIR=$( dirname "$0" )

"$DIR"/whoisping >& /dev/null

"$DIR"/showerrors >& /dev/null
